[theme]
base = "light"
primaryColor = "#8E4B22"
backgroundColor = "#E4D2C0"
secondaryBackgroundColor = "#C7A98B"
textColor = "#2E1B12"

[server]
maxUploadSize = 50
enableCORS = true
enableXsrfProtection = false
