[theme]
base = "light"
primaryColor = "#9B5B2F"
backgroundColor = "#F0E6DB"
secondaryBackgroundColor = "#D9C5B3"
textColor = "#22150F"

[server]
maxUploadSize = 50
enableCORS = true
enableXsrfProtection = false
