[theme]
base = "light"
primaryColor = "#9B5B2F"
backgroundColor = "#F5EEE6"
secondaryBackgroundColor = "#E3D0BE"
textColor = "#2A1B12"

[server]
maxUploadSize = 50
enableCORS = true
enableXsrfProtection = false
